### ISSUE TITLE
post_deploy hook not correctly retrieved

### ISSUE THREAD

**Issue by phoenix-bjoern** [magento/ece-tools#667] opened 2020-01-16 17:07 UTC
When you check the configuration with `vendor/bin/ece-tools wizard:ideal-state` the output is always `Your application does not have the "post_deploy" hook enabled.` In fact the hook is correctly configured in .magento.app.yaml. But the check in src/Config/Application/HookChecker.php reads the setting from a environment variable (ENV_APPLICATION) rather than from .magento.app.yaml. Instead Magento\MagentoCloud\Filesystem\FileList::getAppConfig() should get called to retrieve the setting from the file.

Is my assumption correct?

**Comment by YPyltiai** [comment] 2020-01-16 17:28
Yes, that's correct. We may need to change the logic a bit to get it working on local machines. There was no reliable way to check if it's local or real instance from CLI through ECE-Tools CLI, thus we had to use this workaround.

**Comment by BarnyShergold** [comment] 2020-04-08 13:16
Can we close this issue as it's being dealt with on issue #684 (MAGECLOUD-5295)?

**Comment by ihor-sviziev** [comment] 2020-04-09 12:31
Duplicate of #684

**Comment by YPyltiai** [comment] 2020-04-09 13:50
@BarnyShergold , @ihor-sviziev this one is different - it's about an issue that this command always returns error on local machines (not scenario-based deployment bug). Reopening

**Comment by BarnyShergold** [comment] 2020-04-18 21:09
Is it not reasonable then to change getApplication() in Magento\MagentoCloud\Config\EnvironmentData so that if getEnvVar returns NULL (local machine) that it then tries to read .magento.app.yaml?

I'd quite like to do the PR on this but can we agree this is the correct thing to do before coding is done?

**Comment by BarnyShergold** [comment] 2020-04-20 14:38
@YPyltiai @ihor-sviziev @phoenix-bjoern - Any thoughts on my comment?

**Comment by YPyltiai** [comment] 2020-04-21 20:35
I think it makes sense but would love someone familiar with of post-deploy code to look into it as well. @oshmyheliuk , @shiftedreality , can you see the above comment please ^?

**Comment by oshmyheliuk** [comment] 2020-04-22 13:49
Yes, I agree that this is an issue when ece-tools is running not on the cloud environments as we expect that post_deploy hook always in ENV_APPLICATION variable.
Looks like we need to update our code according to @BarnyShergold suggestion
```
change getApplication() in Magento\MagentoCloud\Config\EnvironmentData so that if getEnvVar returns NULL (local machine) that it then tries to read .magento.app.yaml?
```

**Comment by YPyltiai** [comment] 2020-04-22 17:08
It was initially returning NULL on environments with Prod not in UI but since now every Prod is in UI - I guess we can change it.

**Comment by BarnyShergold** [comment] 2020-04-23 15:11
Code & Unit tests now submitted on #722

**Closed as completed** 2020-05-04 23:54 UTC
Labels: community, improvement
