### ISSUE TITLE
Cron being disabled in 2.4.4 environments

### ISSUE THREAD

**Issue by ssx** [magento/ece-tools#811] opened 2022-07-18 12:08 UTC
We've had a few environments now where the cron is ended up being disabled close to deployments. 

It's only happening with sites that have gone up to 2.4.4 as far as I can tell.

re-enabling the cron with `vendor/bin/ece-tools cron:enable` everything kicks back in and works again.

My workaround for the moment is the add a second cron task to `.magento.env.yaml` to re-enable it every five minutes but I highly suspect something around the deployment process is the cause of the issue.

**Comment by BaDos** [comment] 2022-07-20 19:16
Hi @ssx 
We have created an internal task to investigate and fix this issue: MCLOUD-8999
Thank you!

**Comment by ssx** [comment] 2022-07-21 05:26
@BaDos no problem, i appreciate it'll be a difficult one to track down.

**Comment by aligent-lturner** [comment] 2022-09-19 02:48
We have seen this happen also, but it appears to be an issue whereby the cron is disabled during deployment, and not subsequently re-enabled at the end of the deployment.
The result is `app/etc/env.php` still contains the array entry:
```
cron => [
    enabled => 0
]
```
Deployment logs do not indicate any error with the re-enabling, so either there was an error that got ignored, or another step/process updated the file soon after.

Once the cron has been re-enabled, the issue does not occur until the next deployment.

**Comment by ssx** [comment] 2022-09-19 07:16
> We have seen this happen also, but it appears to be an issue whereby the cron is disabled during deployment, and not subsequently re-enabled at the end of the deployment. The result is `app/etc/env.php` still contains the array entry:
> 
> ```
> cron => [
>     enabled => 0
> ]
> ```
> 
> Deployment logs do not indicate any error with the re-enabling, so either there was an error that got ignored, or another step/process updated the file soon after.
> 
> Once the cron has been re-enabled, the issue does not occur until the next deployment.

Yep, that's identical to what I've seen.

**Comment by ssx** [comment] 2022-09-19 07:17
I should add - it also appears to be happening on 2.4.5 too.

**Comment by BaDos** [comment] 2022-09-19 18:20
@ssx @aligent-lturner 
We found that there was a wrong path in opcache blacklist.
Please check that you have this fixed path https://github.com/magento/magento-cloud/blob/master/op-exclude.txt#L2
And check that your php.ini has this line https://github.com/magento/magento-cloud/blob/master/php.ini#L42

Please leave feedback if it helps.

**Comment by ssx** [comment] 2022-09-20 07:00
I have an idea of what causes this - for us it was environments that have upgraded from starter to pro, the op-exclude.txt file just wasn't present in the reply which caused this issue to show.

**Comment by ssx** [comment] 2022-09-20 07:01
@aligent-lturner by any chance was your env an upgraded one?

**Comment by BaDos** [comment] 2022-09-20 13:02
@ssx so, did adding the op-exclude.txt file and editing the php.ini fix this issue for you?

**Comment by ssx** [comment] 2022-09-20 13:14
> @ssx so, did adding the op-exclude.txt file and editing the php.ini fix this issue for you?

appears to have solved it so far. 

`op-exclude.txt` wasn't present in the repo for us - whether that's due to an old cloud project or the fact it started life as a `starter` package I'm not sure.

**Comment by BaDos** [comment] 2022-09-20 16:05
@ssx maybe you just had the old template.
I'm going to add a validator to ece-tools to check opcache configuration.

Can I close this issue?

**Comment by aligent-lturner** [comment] 2022-09-20 23:15
`op-exclude.txt` was present in our case, but had the incorrect value. Updating it appears to have resolved the issue.

**Comment by BaDos** [comment] 2022-09-21 04:41
@ssx @aligent-lturner thank you for your help!

I will close this issue.
If you face this problem again, please reopen the issue.

**Closed as completed** 2022-09-21 04:40 UTC
Labels: bug, Priority: P0, Progress: done

**Comment by IgorVitol** [comment] 2022-09-21 11:16
@BaDos @ssx @aligent-lturner The root cause is different.

1. After deployment (deploy hook, which you can trigger even locally), the next lines is removed from env.php
![image](https://user-images.githubusercontent.com/4457354/191490179-6b05dc8f-0c71-40e1-ada0-c83e415bd4cf.png)

2. When any graphql endpoint called, next method is used:
`\Magento\GraphQlCache\Model\CacheId\CacheIdCalculator::getSalt`

3. This method is adding a salt to the env.php when it is missing.

4. Since API calls are managed by php-fpm, opcached version of env.php (with disabled cron) was used to modify config file.

Adding **env.php** to the opexclude config solved the issue, but I would say that **env.php** should **NOT** be modified by an API calls. The proper way would be do add a salt during deploy phase or avoid it's reset here (preserve it on redeploys).

Here is the temporary workaround we are using to preserve id_salt during redeploy - add an ENV variable:
![image](https://user-images.githubusercontent.com/4457354/191490387-b5c2a407-764e-461b-8ea9-c7f2f055dc4a.png)

**Comment by BaDos** [comment] 2022-09-21 15:47
@IgorVitol
We had the wrong path in the opcache blacklist and that's a fact.
Regarding the behavior of Magento, please open a bug there https://github.com/magento/magento2/issues

Thank you!

**Comment by IgorVitol** [comment] 2022-09-22 08:31
@BaDos But what about removing graphql cache-related lines in **env.php** (which Magento2 is adding) during deploy hook execution? You want this to be reported as the Magento 2 issue "to not store the flags under 'cache' key"? As an alternative option **ece-tools** could just preserve it during deploy.

**Comment by BaDos** [comment] 2022-09-22 19:13
@IgorVitol you are right. If this key is present in env.php, ece-tools should keeps it.
I will create an internal task.

**Comment by BaDos** [comment] 2022-11-02 00:51
@IgorVitol it was fixed in the latest release 2002.1.13
